[build]
command = "npm run build"
publish = "out"

[build.environment]
NODE_VERSION = "18"
NETLIFY_NEXT_PLUGIN_SKIP = "true"
NEXT_PRIVATE_TARGET = "export"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
